### ISSUE TITLE
"Audio in" feature problem

### ISSUE THREAD

**Issue by incoler** [sskodje/ScreenRecorderLib#106]
I am using version 3.0.
When both "Audio out" and "Audio in" functions are used, the microphone input will not work.
At first, the microphone is recorded normally, but when playing a video, the microphone's voice is not recorded, only the video's sound is recorded.
After that, the microphone voice is not recorded even if the video is ended.

*** Thank you for such a great project

**Comment by athiemailid** [comment]
Hi,

My headphone sample rate of 8000 and channel is 1 (Please see the attached image for your reference.) 

issue occurring, When both "Audio out" and "audio in" devices have a different sample rate value.

Instead of hardcode the sample rate and channel value in Loopback_Capture.CPP, we can get direct sample rate and channel details from both device Endpoint mix format( [https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-formats]() )while selecting an audio device from the test app options.

For example,

From the image, if I select option 1 from speaker details and option 1 from the microphone details, should be work.

**speaker  details**
 
 Option :1 Endpoint Name :L8 Hands-Free AG Audio
          Sample Rate :8000
          Channel :1
          Bit per sample 32

**Microphone**

  Option :1 Endpoint Name: L8 Hands-Free AG Audio
          Sample Rate:8000
          Channel :1
          Bit per sample 32

Could you provide details about, why we need to hard code the value of SAMPLE RATE in Loopback_Capture.CPP?

Thanks for the great support.
![Capture](https://user-images.githubusercontent.com/60776018/99378988-6f15a280-290b-11eb-9842-b3b625ab43a5.PNG)

**Comment by sskodje** [comment]
Hello! The reason the sample rate and bit depth is hardcoded is because the AAC audio encoder is strict on what it accepts. You can see the specs [here](https://docs.microsoft.com/en-us/windows/win32/medfound/aac-encoder). Thus there is a resampler to resample all audio to the same format, else it would not work. Your bits per sample of 32 is not supported for example, neither is a sample rate of 8000.

The issue here is most likely an error in the resampler, as it's really hard to test with all the different equipment people use. If you enable debug logging and set it to "trace" in your recorder options, it should possible give some clues to what is going on.

**Comment by athiemailid** [comment]
Thanks for sharing detailed information.  I have shared the trace log for your reference.  Let me try to fix this issue.
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/5557194/log.txt)
[log_1.txt](https://github.com/sskodje/ScreenRecorderLib/files/5557195/log_1.txt)

**Comment by kmaki565** [comment]
In my side, speaker sound is lost instead, when I use a BT headset which needs resampling. 
[log_Bad.txt](https://github.com/sskodje/ScreenRecorderLib/files/5560946/log_Bad.txt)

Strangely, when I enabled "Trace" logging to a file, the issue was not observed and no error was logged. 
[log_Good.txt](https://github.com/sskodje/ScreenRecorderLib/files/5560961/log_Good.txt)

**Comment by sskodje** [comment]
Thanks for the logs, i'll try to reproduce the issues.

**Comment by sskodje** [comment]
I believe i have identified and fixed the issues. One issue was due to certain combinations of sample rates produced 0 bytes due to an error in a division, and another due some audio samples being resampled twice. An updated nuget should be up shortly.

**Comment by kmaki565** [comment]
Thanks @sskodje , your expertise on multimedia and low level programming help us a lot!

For the BT headset with which I attached failed log, it now captures speaker and mic very clearly. 
Also I tested with another BT headset I have. Though the sound quality was not optimal for the device, it improved a lot to acceptable level.

One suggestion is that would it be possible to enable GitHub Actions for auto build on this project? It would help us isolate such kind of issues. [Example in my projects](https://github.com/kmaki565/EventLook/blob/master/.github/workflows/main.yml)
