### ISSUE TITLE
C# implementation & Cursor click render with WindowsGraphicCapture

### ISSUE THREAD

**Issue by veler** [sskodje/ScreenRecorderLib#110]
Hello,

Congrats for this awesome library!
I have 2 naive questions.

1. I see that the mouse click render is only supported in the implementation details related to Desktop Duplication API. Is it impossible to support it with WindowsGraphicCapture API? It looks like (again, naive question...) it's using similar APIs to treat the frames, what's blocking here?

2. What is the original reason for making the library in C++ instead of C#? Anything preventing to do it in C#? Any concern regarding the performances if the Native library was Managed?

Thanks :-)

**Comment by sskodje** [comment]
1: You see, it's quite technical, the reason is that.. i had forgotten all about it. I'll add it to the bucketlist, unless you want to do a PR?

2: I have no idea, i've never made a c# implementation. I know you can use wrappers like SharpDX and NAudio, which would probably work fine. Personally i just wanted to write it in c++.

**Comment by veler** [comment]
Sounds good, thank you very much :) I was just curious.

If it's not too complicated to support the mouse click render with WindowsGraphicCapture, that would be very nice to have! Perhaps some refactoring would help at merging the code to avoid duplicating the implementation.

**Comment by sskodje** [comment]
Fixed with 8094572c012c0ed5bf68d36a09a62aa11f603ce3
