### ISSUE TITLE
Memory Streams

### ISSUE THREAD

**Issue by Teafuu** [sskodje/ScreenRecorderLib#112]
Hello.

Use Case:
When event raised, save recording from x amount of seconds in the past.

I have sort-of achieved this by having an internal counter that resets the recording every 10 seconds, but this is just doable short term. I tried using the memory streams by seeking with an offset, but this corrupts the recording. Most likely because of missing meta data/file structure that's recorded when a recorder is a setup.

Do you know if there is a way of achieving this? 

Wild brainstorming would suggest that I could save the start of the stream, that has the file-structure/meta data, and then append the incomplete stream. However I have no knowledge of how the mp4 are structured, which is why I'm posting this meaningless thread, in an attempt to get help.

I could also have 2 recorders set up, but I'd rather not since that is gonna take up alot of resources.

Let me know if you have any ideas how a plebian like me could achieve what I would like!

**Comment by sskodje** [comment]
An MP4 is made up of a header (moov) and data packets (mdat). If you enable "fragmented mp4" which is made for internet streaming, the entire header will be in the front, and then the video content will be alternating subheaders (moof) and data packets (mdat). You can see how it is built up [here](https://stackoverflow.com/questions/35177797/what-exactly-is-fragmented-mp4fmp4-how-is-it-different-from-normal-mp4)

It should be possible, with fragmented mp4 enabled, to make a custom stream that will snatch out the header when you start a recording (from start of file to first instance of moof), and then store the last 10 seconds of the stream in an internal memory stream. When you need to save the file, you need to identify the first moof, then copy the header + your content from the first moof until the end of stream to a new file. Unfortunately i don't think it's just THAT easy, because you also would need to modify your streams metadata to make it work, like discussed [here](https://stackoverflow.com/questions/54186634/sending-periodic-metadata-in-fragmented-live-mp4-stream).

Unfortunately i don't have any first hand experience with this.
