### ISSUE TITLE
Send captured stream over the network

### ISSUE THREAD

**Issue by clobotorre** [sskodje/ScreenRecorderLib#167]
I would like to use this lib to capture desktop and audio in real time. Is there any way to read from the stream while it is being filled with the Record method?

**Comment by sskodje** [comment]
To read from the stream you would need to create a custom stream to use as input. In that custom stream you must override the write method and send the packages over the network instead of to file or memory.  The problem is with playing it back, and making it real time, and it will not work without modification to the stream, due to some issues with Media Foundation. You can check if this project for the changes needed to make it work.

https://github.com/forderud/AppWebStream
