### ISSUE TITLE
Screenrecorder dependency issue

### ISSUE THREAD

**Issue by aadithancsg** [sskodje/ScreenRecorderLib#182]
Hi 

We don't have a Media pack in a few of my servers (Windows N) therefore screen recorder never worked there when we click on the start button. However, after upgrading version 3->5 I am getting an error saying unable to find screenrecorder.dll or one of its dependencies immediately when launching my application. It's not letting me open my app at all.  

This happens only with the new version If I go back to the older version I am not seeing that hard stop.  Any suggestions on this. ?

**Comment by sskodje** [comment]
That's odd. It should not require any dependencies just to load. Is it only happening on the machines with Windows N ?

**Comment by sskodje** [comment]
It's weird, because most often this error means either a mismatch between the platform of the exe and the dll (x86 or x64), or an issue with the c++ runtime. Since you say your application works on other machines, there is still a possibility is that it could be the c++ runtime on these machines. Did you try to reinstall the c++ runtime from [here](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) ?

**Comment by aadithancsg** [comment]
I confirmed C++ runtime was there. I have to try to create a VM with a windows server (without media pack) to replicate this issue. I will keep you posted.
