### ISSUE TITLE
Recording file size varies drastically on 4 different machines.

### ISSUE THREAD

**Issue by richardli7** [sskodje/ScreenRecorderLib#21]
Hello, sskodje! I am here again. First of all, I really appreciate you developed this library, fantastic work!
Currently, I am using version 1.1.5, and my code looks like this.

I have deployed the same piece of code on 4 different machines, it is just interesting to see the video sizes are drastically different, I think might due to different bit rate , but for which I have already set to fixed values in the code.

I just want to share with you how they look. It is nice to have to know some knowledge about why they behave in this way. Otherwise, doesn't matter.

![image](https://user-images.githubusercontent.com/20408106/50065012-1e760600-0219-11e9-8b96-d1e363cc660f.png)

By the way, do you accept any donations? I would like to say thank you for providing this great library on the nuget. Please give me your paypal account if that is easy for you?

Cheers,
Richard

**Comment by sskodje** [comment]
Hey!

This was a weird one. 

First off, Media Foundation, The Windows APIs this library uses, picks the video encoder to use based on what the system can support. So if "hardware encoding" is enabled for example, and the system does not have hardware that is capable of encoding h264, it fallbacks to software encoding. This is what i believe is happening to 3 of your 4 PC's, while the 4th encodes on hardware...

...Which leads us to a bug i discovered in Media Foundation where what i believe is happening is that the software encoder does not correctly implement CBR (constant bitrate) encoding, which turns out is the default, and hence fallbacks to VBR (variable bitrate). VBR can greatly reduce the file size on low framerate static content.

This led to the unfortunate situation that hardware encoding runs default in CBR, and software in VBR. I have added a setting to configure the two encoding modes, and set VBR mode as default, so it's equal on both software and hardware. Configuring CBR for software encoder may or may not work depending on the system, and the same goes for hardware. I just don't know. VBR should work.

I'm glad that you have a use for this code, and i'm flattered :) If you wish to make a donation, my paypal is sskodje@hotmail.com.

Fixed with 4132087de1af1c83ae6fec718ce0266995ffdab5

**Comment by richardli7** [comment]
Thumb up!

**Comment by richardli7** [comment]
Hi sskodje,

The new change seems not working for all machines, mine here, the remaining working one is a virtual machine. 

![image](https://user-images.githubusercontent.com/20408106/50256169-e7dafe00-0459-11e9-8957-32a5b67f5bb3.png)

**Comment by richardli7** [comment]
Yes, the deployment I did was only replacing the screen record lib.dll and the XML.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sskodje** [comment]
This is very strange. Does it help at all if you change the mode to CBR?

**Comment by richardli7** [comment]
How do I make the mode change to CBR?
Do I just set IsFixedFramerate to 'false' instead of 'true'?

Hang on, I will try that one out.

**Comment by sskodje** [comment]
I unlisted it while i figure this out. You can install from package manager console in visual studio with 
"Install-Package ScreenRecorderLib -Version 1.1.6". You can change the bitrate mode in VideoOptions by setting the BitrateMode property.

**Comment by richardli7** [comment]
right. I succeeded in installing 1.1.6 back, and I tried to set BitrateMode in either BitrateControlMode.CBR and the default mode, could it be something else than BitrateMode?

![image](https://user-images.githubusercontent.com/20408106/50264635-634fa600-0480-11e9-8549-0a8ec13495cd.png)

**Comment by sskodje** [comment]
Do you get any errors at all?

**Comment by richardli7** [comment]
The file size you sent is identical with my 1.1.6, I had it a go, seems not working, but I can't be sure if I am using your modified lib. Any suggestions?

**Comment by sskodje** [comment]
It was just a very minor modification, so the size is the same. It was a crapshoot anyway. I'm going to test this further on a few more machines over christmas. You can configure version 1.5 to disable hardware encoding, and you should get the same, low file size on all your machines as well.

**Comment by sskodje** [comment]
I've updated to version 1.1.7 on Github and Nuget, and i believe this issues that is related to codecs is fixed. Please give me a shout if that is not the case.

**Comment by richardli7** [comment]
Hi Skodje,

Thank you very much!

Ruchard

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
