### ISSUE TITLE
Recording games is a bit laggy

### ISSUE THREAD

**Issue by Pietro228** [sskodje/ScreenRecorderLib#211]
Hi,

I tried to record World Of Tanks but it's little bit laggy and it keeps the video on 53 FPS instead of 60.
I have a fixed framerate.

**Comment by sskodje** [comment]
Games can use so much of the system resources, it causes recordings to drop frames, especially on high resolutions and framerates. Using hardware encoding can help if the CPU is weaker than the graphics card, and vice versa, if the CPU is stronger than the graphics card, disabling hardware encoding may help.

**Comment by sskodje** [comment]
I'll reopen and do some benchmarks. It could the scaling from 2.5k to 1080p.

**Comment by sskodje** [comment]
This issue should be fixed with 01a88e3bfed1116626f99057a87ff7927dafeea3 and d2a99598d45a098cad0bed79241a058085f3ba55. The first issue was a race condition causing dropped frames under high cpu load, while the second was missing hardware acceleration of a texture conversion. Thanks for pointing me in the direction of these bugs, and hope it works better for you now :)
