### ISSUE TITLE
Recording colors are getting reverted

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#226]
I have tried the recorder on a Windows 10 22H2 PC. Interestingly the colors of recording are reverted to redish tone.

https://user-images.githubusercontent.com/92986100/218127022-3e63ca62-b125-4e9c-944d-8879e3fb5e1e.mp4

**Comment by ranwer-dev** [comment]
On another PC, it's all green. Any idea what could be causing this? 
![image](https://user-images.githubusercontent.com/92986100/228186483-eb5fa747-a4b3-4fb6-b23c-c215830f861d.png)

**Comment by sskodje** [comment]
The green color is what happens when you send empty data to H264 encoder. E.g a pixel with colors [0,0,0] becomes green. So it means something goes wrong somewhere and it sends empty junk data. The pink and green issue i don't know, but it's probably because there's a mismatch between the format the encoder receices, and what it expects. I've seen it before on HDR content without playback support.
