### ISSUE TITLE
IsMp4FastStartEnabled option doesn't work when IsFragmentedMp4Enabled option is also used

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#234]
If we use both IsMp4FastStartEnabled  & IsFragmentedMp4Enabled  options, video doesn't faststart. Is there any way to fix this?

**Comment by sskodje** [comment]
Fast start is unfortunately quite broken, because Microsoft Media Foundation is broken in this regard. I've been working on a fix.

**Comment by sskodje** [comment]
Fast start is unfortunately still fundamentally broken in Media Foundation. Fragmented mp4 should work though, even though fast start does not. The two flags are mutually exclusive as far as i know.

**Comment by sskodje** [comment]
That's good fast start works for you, but I'm a bit confused what your issue is then.

Fast start is only meaningful when streaming non-fragmented mpegs however. What it does is to write the headers at the start of the video instead of at the end, so you don't have to download the entire video to start streaming. Fragmented mpegs already fully support streaming due to their fragmented nature, and thus the flag does nothing by design. The headers in a fragmented mpeg are written periodically every few seconds.

Do you have a specific issue with streaming videos recorded with any of the flags?
