### ISSUE TITLE
camera preview is available in future? 

### ISSUE THREAD

**Issue by selvacreation** [sskodje/ScreenRecorderLib#254]
Recently, I used your library, and it's working great. The camera is also functioning well. However, I am unable to preview the webcam. Is it possible that a camera previewing feature will be available in the future or in next version ?

**Comment by sskodje** [comment]
It depends on what your requirements are. I'm working a feature that will allow you to get the raw bitmaps instead of or in addition to recording to video. You could draw those in your app, but for technical reasons they will only be delivered while recording, and it will be most likely be heavy on the CPU as it will need to be software drawn.

**Comment by selvacreation** [comment]
No, I am asking if, while recording through the webcam, the user needs to see what is happening on the screen (for example, like the preview in a camera app). That's what I am asking.
