### ISSUE TITLE
Abrupt end of recording and corrupted video

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#261]
This doesn't happen all the time, but in some rare cases, recording starts and then after a few seconds or minutes it abruptly ends. Which leaves behind an unplayable video. What could be the reason?

**Comment by sskodje** [comment]
If you enabled detailed logging and capture an error, i could take a look at it. It's impossible to answer without more to go on.

**Comment by HariPrasath1107** [comment]
Hi, 
For me when I initiate my build the build is running successfully, and the video is getting recorded at the first instance and the video is playable as well.
But when I tried for the 2nd instance build is getting succussed, but the video recorded is not playable it is getting corrupted and throwing the error while playing I have attached screenshot for it.
The build is working in the same way which got ran in the previous instance, but the recording is not playable.
Can anyone advice encountered this issue, could anyone advice on this?

_**Error message "We can't open TC299236.mp4. This may be because the file type is unsupported, the file extension is incorrect, or the file is corrupt.
0x00003604".**_

![image (1)](https://github.com/sskodje/ScreenRecorderLib/assets/161283891/db77131a-1868-406e-af00-baae9c5ab7e4)
