### ISSUE TITLE
Question: Could you share all temhe resources that you used to create this library and learn about dx?

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#270]

**Comment by sskodje** [comment]
If you want to learn about DirectX, there's plenty of tutorials out there, as it's very popular for game development. If you want to learn about Media Foundation and COM, there's not really that much in the way of tutorials. You have the [official documentation and samples](https://learn.microsoft.com/en-us/windows/win32/medfound/microsoft-media-foundation-sdk), otherwise you pretty much just have to check out projects on github for code examples, stack overflow, and i can recommend the use ChatGTP.
