### ISSUE TITLE
Hello, is it possible to be backward compatible with the program of .net framework (4.0 or 4.6).

### ISSUE THREAD

**Issue by xuechengang** [sskodje/ScreenRecorderLib#271]
Hello, is it possible to be backward compatible with the program of .net framework (4.0 or 4.6).
///
Failed to resolve the main reference 'ScreenRecorderLib' because it was against ". NETFramework, Version=v4.6.2". The framework version is higher than the current target framework". NETFramework,Version=v4.6”。

**Comment by sskodje** [comment]
The release is compiled against is .net framework 4.6.2, because that's the oldest version supported by Microsoft. If you need to compile for legacy versions, you can change `<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>` in `ScreenRecorderLib.vcxproj` to for example `<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>`. You also need to have the correct .net framework target pack installed for Visual Studio.
