### ISSUE TITLE
Non GPU Machines Options not working

### ISSUE THREAD

**Issue by kasirajansfm** [sskodje/ScreenRecorderLib#298]
Build an EXE with below options on Windows 10 with GPU machine,

![image](https://github.com/sskodje/ScreenRecorderLib/assets/166936661/2cd7b15e-9be3-4545-9d51-13cbeae14e0a)

its approximate file size is around 400kb. When i try to run same EXE on Windows 10 Non-GPU machine, the file size is around 1.8MB is there anything am missing on my code.? anyone faced this kind of issue?

**Comment by sskodje** [comment]
Hello! The different encoders have different opinions of things, and one of them is the Quality BitrateMode option. I have noticed the Microsoft sofware encoder will in many cases use a higher bitrate given the same quality number than hardware encoders. 

Your code has set the bitrate for the encoder, but you also must set the encoder in "constat bitrate" or CBR mode, for that option to have effect. Quality and Bitrate is mutually exclusive.

For quality (this is default, which is why it works if omitted)
```csharp
                    VideoEncoderOptions = new VideoEncoderOptions
                    {
                        Encoder = new H264VideoEncoder { BitrateMode = H264BitrateControlMode.Quality },
                        Quality = 30
                    }
```
for CBR:
```csharp
                    VideoEncoderOptions = new VideoEncoderOptions
                    {
                        Encoder = new H264VideoEncoder { BitrateMode = H264BitrateControlMode.CBR},
                        Bitrate = 50000
                    }
```
