### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by Stealth01** [sskodje/ScreenRecorderLib#41]
Is it possible to show the captured video in a image control (or some other control) in real time, without writing it to a file?

**Comment by sskodje** [comment]
I have never tried, but if you want to attempt it, first you have to set IsFragmentedMp4Enabled to true. This writes the mp4 header periodically instead of at the start/end of the file, so you can start the stream from wherever and play it back while it is encoding. Then you would have to pass a stream that supports seeking to the Record method, and set that stream as input in a videoplayer that supports playing from a stream.

**Comment by Ahmad45123** [comment]
> as input in a videoplayer that supports playing from a stream.
Can you please point me to an easy way to do this ? I've googled a lot and all of them point to me having to do it manually with Media Foundation or Direct Show which is kind of hard with my 0 knowledge of C++ :/

**Comment by Ahmad45123** [comment]
@sskodje The idea is that I want to play/decode a byte stream directly without having to write to a file.

**Comment by Stealth01** [comment]
If your goal is to capture the screen and show it in a form (or a control like a panel), I did it using SharpDX.
I adapted the code of the [ScreenCapture sample](https://github.com/sharpdx/SharpDX-Samples/tree/master/Desktop/Direct3D11.1/ScreenCapture) by adding a loop (to capture frames continuously) and drawing the acquired frames on the form, instead of saving them on a file.

**Comment by Ahmad45123** [comment]
https://github.com/unosquare/ffmediaelement
I ended up using this actually.. pretty promising
