### ISSUE TITLE
About Mouse Click

### ISSUE THREAD

**Issue by LKMMKL** [sskodje/ScreenRecorderLib#42]
I'm a little confused, sometimes click the mouse, click the effect will not show, there is uncertainty.
I use the following interface:
[DllImport("user32.dll")]
public static extern void mouse_event(...);

**Comment by sskodje** [comment]
It seems to work for me with the crude test i made. Please post your code for generating clicks if it still isn't working.

        [DllImport("user32.dll", CharSet = CharSet.Auto, CallingConvention = CallingConvention.StdCall)]
        public static extern void mouse_event(uint dwFlags, int dx, int dy, int cButtons, int dwExtraInfo);
        private const uint MOUSEEVENTF_LEFTDOWN = 0x02;
        private const uint MOUSEEVENTF_LEFTUP = 0x04;
        private const uint MOUSEEVENTF_RIGHTDOWN = 0x08;
        private const uint MOUSEEVENTF_RIGHTUP = 0x10;

        void sendMouseDown()
        {
            mouse_event(MOUSEEVENTF_LEFTDOWN, 50, 50, 0, 0);
        }

        void sendMouseUp()
        {
            mouse_event(MOUSEEVENTF_LEFTUP, 50, 50, 0, 0);
        }
          private void StartTest()
          {
           Task.Run(async () =>
             {
                 await Task.Delay(1000);
                 while (true)
                 {
                     sendMouseDown();
                     await Task.Delay(20);
                     sendMouseUp();
                     Debug.WriteLine("Mouse clicking");
                     await Task.Delay(2000);
                 }
             });
           }

**Comment by LKMMKL** [comment]
Thanks for your quick response.
I use the following code. It seem nothing different.
private const uint LeftDown = 0x02;
private const uint LeftUp= 0x04;
mouse_event((int)(LeftDown | LeftUp), 0, 0, 0, UIntPtr.Zero);

**Comment by sskodje** [comment]
Well i've discovered the issue at least. There are two ways to discover global mouse clicks, one is by polling, and one is by a low level system hook. The system hook negatively affects mouse performance, as well as freezing the mouse on debug break, so the polling system is currently used.  Unfortunately when you call mouse_event(LeftDown | LeftUp), it "clicks" the mouse so fast that the polling system misses it. That's why it worked with a delay between LeftDown and LeftUp.

I'm not sure what to do about this. Perhaps i'll add a choice between polling or hook.
 As a workaround in the meantime, it should work if you put a delay between down and up as in my sample.

**Comment by LKMMKL** [comment]
Thank you for pointing out the problem.I will try to use your method.Expect more features to appear in  your project.

**Comment by sskodje** [comment]
I added this feature with https://github.com/sskodje/ScreenRecorderLib/commit/4fbb9ceed6ef96d2c2994ed5b247e56533b1f39e
