### ISSUE TITLE
Abort double click

### ISSUE THREAD

**Issue by LKMMKL** [sskodje/ScreenRecorderLib#58]
It seems can't show color when I double click ,like this:
`         mouse_event((int)(Win32API.MouseEventFlags.LeftDown), 0, 0, 0, UIntPtr.Zero);
            Thread.Sleep(500);
            mouse_event((int)(Win32API.MouseEventFlags.LeftUp), 0, 0, 0, UIntPtr.Zero);
            mouse_event((int)(Win32API.MouseEventFlags.LeftDown), 0, 0, 0, UIntPtr.Zero);
            Thread.Sleep(500);
            mouse_event((int)(Win32API.MouseEventFlags.LeftUp), 0, 0, 0, UIntPtr.Zero);
`
May be It's the bad time  to use sleep().
I really look forward to your good advice ,thanks !

**Comment by sskodje** [comment]
The reason is there are no delay between your mouse down event and mouse up event, and you have configured the library to use polling.

There are two configurable ways to detect mouse clicks in the library, system hook and with polling.

System hook: All mouse events are routed through your application. This will pick up every mouse events like your programmatic events, but it can affect your mouse performance. If your application hals, so will the mouse. E.g. on a debug break.

Polling: It checks for mouse events every millisecond. Will pick up any human input, but can miss programmatic inputs with no delay between mouse down and up. If the system hook is not acceptable for your use case, you can put a sleep between mouse down and mouse up for two milliseconds, like this:

            mouse_event(MOUSEEVENT_LEFTDOWN, 500, 500, 0, 0);
            Thread.Sleep(2);
            mouse_event(MOUSEEVENTF_LEFTUP, 500, 500, 0, 0);
            Thread.Sleep(50);
            mouse_event(MOUSEEVENT_LEFTDOWN, 500, 500, 0, 0);
            Thread.Sleep(2);
            mouse_event(MOUSEEVENTF_LEFTUP, 500, 500, 0, 0);
