### ISSUE TITLE
Error: Failed to create temp folder

### ISSUE THREAD

**Issue by AllNickNamesAreBusySoITakenThis** [sskodje/ScreenRecorderLib#6]
Hello sskodje! Very cool lib, but I always det an error while try to start recoding? Why is this happen?

**Comment by sskodje** [comment]
Hey!

This error may happen when the library tries to create the output folder, but it fails to do so. It may be because you do not have write permission, the path is illegal, the folder is read only, etc.

If you use a folder like the windows temp directory with Path.GetTempPath(), you should always have access.

**Comment by AllNickNamesAreBusySoITakenThis** [comment]
Thanks! thats helped! 
Did you test this lib on Windows 7?

**Comment by sskodje** [comment]
Good to hear. The library is using Desktop Duplication API, which was introduced in Windows 8, so unfortunately Windows 7 is not supported.
