### ISSUE TITLE
Fail when run against discrete GPU

### ISSUE THREAD

**Issue by diegoadan** [sskodje/ScreenRecorderLib#63]
Hello guys, it is a great Lib, thanks for the great job done. Just want to inform about an issue, this Lib fails to work on hybrid systems with a discrete GPU as stated on the following page:

https://support.microsoft.com/nb-no/help/3019314/error-generated-when-desktop-duplication-api-capable-application-is-ru

Do you know about any workaround to force the app to run on the Integrated Graphics Device?

Thanks again,

**Comment by sskodje** [comment]
That is an unfortunate issue indeed. I fon't know if you can force a graphics card in code, but you can do it in windows as detailed here

https://answers.microsoft.com/en-us/windows/forum/all/select-gpu-to-use-by-specific-applications/eb671f52-5c24-428d-a7a0-02a36e91ee2f

**Comment by name1ess0ne** [comment]
Hello guys,
I have same issue on one of my machines. I have spent some time investigating this issue and maybe there could be programmatic solution starting from Window 10 v1803.
https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/nf-dxgi1_6-idxgifactory6-enumadapterbygpupreference
The trick is to use `EnumAdapterByGpuPreference` with `DXGI_GPU_PREFERENCE_MINIMUM_POWER` instead of `EnumAdapters`. That will not solve the problem for all users, but at least it helps those who use latest versions of Windows 10.

Also this may be interesting:
https://www.freemancw.com/2020/11/desktop-duplication-on-hybrid-graphics-systems/
