### ISSUE TITLE
Memory leak in 2.0 nuget pacage

### ISSUE THREAD

**Issue by testniracun** [sskodje/ScreenRecorderLib#69]
Hello. 

**1.**
I have found memory leak, when recording video. When I start recording memory is allocated and when I dispose (Recorder _rec;) memory is not released.
I'm using win 10, visual studio 2019 and C# forms application project, x64.
I have used nuget 2.0, build dll from project 2.0, 1.9, 1.8 and 1.6.
For test you can do while loop where you start recording and after 10 second stop.
I added my C# class which sets up recorder.
[test.txt](https://github.com/sskodje/ScreenRecorderLib/files/4769738/test.txt)

`
ScreenRecorderClass X = new ScreenRecorderClass(path);
X.RecorderStatus_Event += X_RecorderStatus_Event;
while(true)
{         
X.CreateRecording(display, 0,0,500,500);
Thread.Sleep(10000);
X.EndRecording();
}
`

**2.**
When I select RecorderOptions->RecorderMode->Snapshot and set DisplayOptions to only some part of screen, you take picture of whole screen. Could you improve this to take snapshot only of specified part of screen? So it will work similar as Video mode.

**Comment by sskodje** [comment]
Thanks for reporting the issue. I'll fix the snapshot for the next version, and check if anything leaks memory.

**Comment by sskodje** [comment]
This should be fixed with c8cc8de9bb55c6412a5bb2f3734880f39679d4c3 and 9bfb9991424dcabd9499930e3cc30e0e09af6448

**Comment by testniracun** [comment]
Memory leak still in 2.3. 
If I download nuget package I get access violation exception, when stop recording.
If I use project from git it works ok, but there is still memory leak.

**Comment by sskodje** [comment]
I that case i think there must be errors that prevents the library from cleaning up resources. The reason you don't get error when using the library from git is because such errors often only manifest themselves when building for relase, due to the optimalizations done. 

This is unfortunately not all that uncommon, since Windows uses third party drivers for video encoding, which often misbehaves. I suggest you make sure your video drivers are up to date, and also windows update.

**Comment by testniracun** [comment]
Windows is updated, 1909. I use drivers from windows update.
