### ISSUE TITLE
NuGet packages since 1.1.1 don't add a project reference to ScreenRecorderLib.dll

### ISSUE THREAD

**Issue by icnocop** [sskodje/ScreenRecorderLib#82]
Hi.

Thank you for ScreenRecorderLib.

In a Visual Studio 2017 C# Class Library project targeting .NET 4.6 and "Any CPU", trying to add a ScreenRecorderLib NuGet package above 1.1.1 doesn't add a project reference to ScreenRecorderLib.dll as expected.

It works with 1.1.0 without issues.

*** Edit ***
It seems this is because the msbuild `<Reference>` elements are inside an msbuild `<Target>` element.

So now I'm just wondering if that's necessary, and why?

Thank you.

**Comment by sskodje** [comment]
Hello!

This library will never be able to work with "Any CPU", because it is C++ based, while "Any CPU" is a .net feature. As such, it needs to choose either x86 or x64 file, which is what the "target" file is doing,  it injects into msbuild, and loads the correct file. If it seemingly works with the very old NuGet package, it is because it by chance picked the correct file that matched your .exe. The old nuget file was simply not set up properly.
